/* =====================================================================
   DATA — this is the part you own. Edit this file only; index.html
   never needs to change when you add, remove, or fix a resource.

   This map starts scoped to Hernando County, FL, but the schema is built
   to grow — statewide, then national — the same way the cyber resource
   maps did. That's why every row carries `county` and `st` even though
   today they're all "Hernando" / "FL": it's what a future regions.js /
   state drill-down would key off, without ever touching this file's shape.

   How to add a row:
     1. Get lat/lng from a real geocoder (US Census Bureau geocoder —
        geocoding.geo.census.gov — or Nominatim/OpenStreetMap) or by
        right-clicking the spot in Google Maps. NEVER estimate/eyeball a
        coordinate for a resource a homeless or at-risk person might
        actually try to walk or ride a bus to — a wrong pin sends someone
        to the wrong building. Exception: confidential shelter locations
        (domestic-violence shelters) — see Dawn Center below — where the
        pin is deliberately generalized to the city center for safety and
        the notes say so explicitly.
     2. category — one of:
          hub      multi-service anchor (3+ distinct aid types under one
                    roof/org — food + medical + casework, etc.)
          food     food pantries, meal programs, mobile food distribution
          shelter  emergency/transitional shelter, domestic-violence
                    shelter — anywhere with actual overnight beds
          clothing thrift stores / free-clothing & household-goods
                    voucher programs
          medical  free/low-cost clinics
          coalition coordinating/advocacy agencies (CoC lead, task forces)
          transportation bus/paratransit systems
          pet      pet food pantries
          hotline  phone-first intake/crisis lines with no single
                    physical address people visit
          workspace free public workspace — computers, job search, meeting
                    rooms (libraries, CareerSource); also where a real
                    commissary/shared-use kitchen would go if one is ever
                    confirmed inside the county (none found as of this
                    sweep — see README)
          hygiene  shower access — gyms (by cheapest membership found) and
                    any free public shower option
          camping  legally designated public camping — state forest primitive
                    zones and developed campgrounds. NOT general "public
                    land" — only actual designated, permitted camping
                    areas. WMA land where overnight camping is explicitly
                    NOT permitted (e.g. Chassahowitzka WMA proper) is
                    deliberately excluded, not implied as an option
     3. county / st — "Hernando" / "FL" today; keep populated on every
        row so a future statewide pass can filter/group by it immediately.
     4. url / address / phone / when / org may be "" or omitted if
        unknown — the popup simply omits empty fields. Never guess
        contact details.
     5. services: [...] — OPTIONAL, cross-cutting need tags, independent
        of category (same idea as the cyber map's `topics`). Fixed
        taxonomy: food, shelter, medical, clothing, financial,
        transportation, petfood, snap, veterans, seniors, children,
        casework, legal, dv (domestic violence), housing, energy
        (utility assistance), headstart, mentalhealth, workspace, showers.
        Only tag what's actually confirmed offered — don't guess.
     6. events: [{ title, when, topics:[] }] — OPTIONAL, named programs run
        out of one location on their own schedule (e.g. PHP's Neighborhood
        Blessings vs. its Tuesday medical clinic). Pulled only from the
        org's own published info, never invented.
     7. verified: "YYYY-MM-DD" — OPTIONAL, date this specific row was
        independently confirmed via the org's own site/a fresh search
        (not just carried over from an older compiled list). Rows without
        it should carry a call-ahead caveat in notes instead.
     8. idRequired: plain-language string — REQUIRED on every `shelter`-
        category row (optional elsewhere). What someone actually needs to
        show up with, sourced from the org's own site where possible.
        "None published — appears low-barrier" is an honest, legitimate
        value when no requirement could be found; never leave it blank
        and never assume a photo ID is required just because that's the
        norm elsewhere — several of this county's shelters explicitly
        do NOT require one (that's a deliberate low-barrier-access
        practice at DV shelters especially, not an oversight).

   Data sweep: August 2026, third pass same month (added camping and a
   phone-verification confidence pass — no calling capability exists in
   this environment, so "verified" below means cross-checked against an
   independent source, never an actual phone call; two rows carry an
   explicit CONFIDENCE NOTE in their `notes` where only one source could
   be found for a number — Salvation Army's Spring Hill line and Esther's
   House's extension). The county's own
   pantry-sheet source (compiled by People Helping People) is dated
   October 2021 — every church/pantry row sourced ONLY from that sheet
   says so in its notes and has no `verified` date. Call ahead before a
   special trip; volunteer-run pantry schedules drift as churches change
   staff. Anchor orgs and everything added in the second pass (shelters,
   coalitions, workspace, hygiene/gyms, veterans and mental-health
   support) were independently sourced this sweep — via the orgs' own
   sites, the Mid Florida Homeless Coalition, and a congressional-office
   community resource guide (bilirakis.house.gov) — and carry a
   `verified` date. SECOND-PASS CORRECTION: the Salvation Army's Hernando
   County Corps relocated from Brooksville to 342 Beverly Court, Spring
   Hill in July 2025 — the old Cortez Blvd address/hours from the first
   sweep were wrong by the time of this pass; fixed below. Two entries
   (Life Center of Hernando, and the youth crisis shelter run by Youth &
   Family Alternatives) intentionally use a generalized city-center pin
   rather than a residential/shelter street address, same safety pattern
   as the Dawn Center — see their notes.
   ===================================================================== */
const RESOURCES = [

  // ---- MULTI-SERVICE HUBS ----
  { name:"People Helping People (PHP) — Kass Circle HELP Center", category:"hub", county:"Hernando", st:"FL", lat:28.45322, lng:-82.59450, city:"Spring Hill", url:"https://www.phphernando.org", address:"1396 Kass Circle, Spring Hill, FL 34606", phone:"(352) 686-4466", org:"People Helping People in Hernando County, Inc.", verified:"2026-08-03", services:["food","medical","casework","snap","shelter"], notes:"Hernando County's only community resource/HELP Center — hot meals, showers, hygiene items, camping supplies for the unsheltered, free Wi-Fi. Two directory listings disagree slightly on general office hours (one says Tue/Fri 10am–2pm only) vs. the program-specific times below — call to confirm before a special trip. Email admin@phphernando.org.", events:[
    { title:"Neighborhood Blessings (hot meals, showers, hygiene, camping supplies)", when:"Tue & Fri lunch 11:30am–12:30pm; Sunday hot meal 3:30–4:30pm" },
    { title:"PHP Health Clinic (free medical, uninsured Hernando residents)", when:"Tuesdays, 10am–1pm" },
    { title:"Mobile Food Distribution (drive-through, w/ Feeding Tampa Bay)", when:"Last Wednesday of each month, ~9am–1pm (cars start moving ~10:30am)" },
    { title:"Weekend Blessings (kid-friendly weekend food backpacks)", when:"Ongoing during school year" },
    { title:"Senior Blessings (monthly supplemental grocery bags)", when:"Monthly" },
    { title:"SNAP application help", when:"By appointment — call to schedule" }
  ]},
  { name:"Mid-Florida Community Services — You Thrive Florida (Hernando HQ)", category:"hub", county:"Hernando", st:"FL", lat:28.54516, lng:-82.37345, city:"Brooksville", url:"https://youthrivefl.org/location/hernando-county/", address:"820 Kennedy Blvd, Brooksville, FL 34601", phone:"(352) 796-1425", org:"Mid-Florida Community Services, Inc.", verified:"2026-08-03", services:["transportation","seniors","children","energy","housing","headstart"], notes:"Runs Trans-Hernando paratransit (see Transportation below), Head Start, Senior Services, the Weatherization Assistance Program, the Children's Advocacy Center, and House to Home. Statewide info line 1-888-802-7483.", events:[
    { title:"Head Start", when:"(352) 754-2464" },
    { title:"Children's Advocacy Center", when:"(352) 754-8809" },
    { title:"Trans-Hernando paratransit reservations", when:"(352) 799-1510, by noon the business day prior" },
    { title:"Senior Services", when:"(352) 796-1426" },
    { title:"Weatherization Assistance Program", when:"(352) 796-1427" }
  ]},
  { name:"Catholic Charities, Diocese of St. Petersburg — Hernando Office", category:"hub", county:"Hernando", st:"FL", lat:28.48733, lng:-82.58198, city:"Spring Hill", url:"https://www.ccdosp.org", address:"8370 Forest Oaks Blvd, Spring Hill, FL 34606", phone:"(352) 686-9897", org:"Catholic Charities, Diocese of St. Petersburg", verified:"2026-08-03", services:["financial","housing","casework"], notes:"Mon–Fri 8am–5pm. Emergency financial/rent/utility assistance, Pathways rapid rehousing, housing counseling, immigration services, Foundations of Life pregnancy/parenting support, and the St. Teresa Apartments (Shelters of Hope) — one-bedroom affordable housing for low-income Hernando County residents. Availability of any given program varies — call to ask what's currently active. Their larger regional shelters (Pinellas Hope, Pasco Women's Shelter) are outside Hernando County but reachable through casework referral." },
  { name:"St. Vincent de Paul — Hernando/Citrus District Thrift Store & Food Pantry", category:"hub", county:"Hernando", st:"FL", lat:28.45339, lng:-82.59627, city:"Spring Hill", url:"", address:"1291 Kass Circle, Spring Hill, FL 34606", phone:"(352) 688-3331", org:"St. Vincent de Paul (SVDP)", verified:"2026-08-03", services:["clothing","food","casework"], notes:"Store hours Mon–Thurs 9am–4pm, Fri 8am–4pm, Sat 9am–1pm (closed Sun). Food pantry drive-thru Tues–Sat 9am–2pm. Free clothing/household vouchers for people in real need are issued through parish-based \"Conference\" casework (e.g. St. Theresa Conference, (352) 688-9997) — call ahead and ask to connect with a home visit/voucher rather than just walking in." },
  { name:"Salvation Army — Hernando County Corps (Spring Hill)", category:"hub", county:"Hernando", st:"FL", lat:28.44093, lng:-82.63576, city:"Spring Hill", url:"https://hernando.salvationarmyflorida.org", address:"342 Beverly Court, Spring Hill, FL 34606", phone:"(352) 796-1186", org:"The Salvation Army", verified:"2026-08-03", services:["food","clothing","financial","casework"], notes:"Relocated here from a 40-year home at 15464 Cortez Blvd, Brooksville — moved July 2025, ribbon-cutting May 2026, because most pantry clients were already coming from the Spring Hill side of the county. Food pantry now Mon/Wed/Fri 9am–1pm (updated from the old Brooksville-era Tue-only schedule). Caseworkers here can help with SNAP, housing referrals, and can issue emergency vouchers for free clothing/furniture/housewares redeemable at the Family Store — ask about voucher eligibility before going to the store. CONFIDENCE NOTE: the phone number is carried over from the old Brooksville office — the new Spring Hill site's own contact page wasn't independently reachable to re-confirm it still rings there, and no phone-verification capability exists to call and check. Try 1-800-SAL-ARMY (national line, confirmed on the org's own site) if this number doesn't connect." },
  { name:"Hernando County Health & Human Services", category:"hub", county:"Hernando", st:"FL", lat:28.55555, lng:-82.39306, city:"Brooksville", url:"https://www.hernandocounty.us/living-here/housing-supportive-services/health-and-human-services", address:"621 W Jefferson St, Brooksville, FL 34601", phone:"(352) 540-4338", org:"Hernando County Government", verified:"2026-08-03", services:["snap","financial","casework","housing"], notes:"General county intake point for WIC vouchers, SNAP outreach, utility/rent assistance, ACCESS Florida benefits connections, and Meals on Wheels referrals." },

  // ---- SHELTER (real overnight beds) ----
  { name:"Jericho Road Ministries — Men's Shelter (Mondon Hill)", category:"shelter", county:"Hernando", st:"FL", lat:28.55647, lng:-82.37537, city:"Brooksville", url:"https://www.jericho-road.net", address:"1090 Mondon Hill Rd, Brooksville, FL", phone:"(352) 799-2912", org:"Jericho Road Ministries", verified:"2026-08-03", idRequired:"No ID requirement found in any source. STALENESS FLAG: this facility/name is sourced from a multi-year-old news article and third-party directories — Jericho Road's own current website (checked 2026-08 for this pass) describes only \"Joshua's House\" as its men's residential facility, as part of a 5-to-25-month recovery program, and never mentions \"Mondon Hill\" by name or a walk-in emergency-shelter model for men. This may be the same facility under an old name, a distinct property still in quiet operation, or discontinued — genuinely unclear from available sources. Call before relying on this as a same-night option.", services:["shelter","food"], notes:"Previously described (via third-party shelter directories, not the org's own site) as an emergency daily shelter for homeless men — ~14 beds, meals and clothing, entry point to Jericho Road's recovery program. See the idRequired staleness flag — verify this is still active and still low-barrier before counting on it for a same-night stay; Joshua's House below is the facility Jericho Road's own site currently describes for men." },
  { name:"Jericho Road Ministries — Mary's House (Women's Shelter) & Jericho Food Barn", category:"shelter", county:"Hernando", st:"FL", lat:28.57268, lng:-82.37867, city:"Brooksville", url:"https://www.jericho-road.net", address:"1163 Howell Ave, Brooksville, FL 34601", phone:"(352) 799-2912 ext 112 or 109", org:"Jericho Road Ministries", verified:"2026-08-03", idRequired:"No ID requirement found in any source — call for a screening interview instead. Like Mondon Hill above, Mary's House is not named on Jericho Road's own current website (which only describes the longer REbuilt recovery program) — treat the details below as sourced from third-party directories, not the org itself, and confirm by phone.", services:["shelter","food"], notes:"Per third-party shelter directories: up to 3 days of emergency shelter for women (bed count varies by source, commonly cited as 6), after which clients must commit to one of Jericho Road's recovery programs to continue staying. The Jericho Food Barn pantry runs from the same campus, Tues & Fri 9am–noon (must have Hernando Co. ID for the FOOD PANTRY specifically — that ID requirement is well-sourced; it's the shelter side that's unconfirmed on the org's current site)." },
  { name:"Jericho Road Ministries — Joshua's House (REbuilt Recovery Program, men)", category:"shelter", county:"Hernando", st:"FL", lat:28.56544, lng:-82.37551, city:"Brooksville", url:"https://www.jericho-road.net/recovery", address:"11014 Broad St, Brooksville, FL 34601", phone:"(352) 799-2912", org:"Jericho Road Ministries", verified:"2026-08-03", idRequired:"No photo-ID requirement published. Real gate instead: 18+, must already be medically detoxed (this is not a detox facility), willing to commit to the full 5-month minimum program, and passes a phone pre-screening interview.", services:["shelter"], notes:"NOT a walk-in/same-night emergency shelter — this is Jericho Road's men's residential facility for the REbuilt recovery program, a 5-to-25-month structured journey (first 3 months education-focused, no outside employment permitted; by month 5 the goal is employment). Apply via the Recovery Program Request form at jericho-road.net/get-help, then a staff phone interview, then notification of a spot or waitlist. ~30 beds, a remodeled former church funded by a $400,000 grant. Free — funded by donors." },
  { name:"Dawn Center of Hernando County — Domestic Violence Emergency Shelter", category:"shelter", county:"Hernando", st:"FL", lat:28.5544, lng:-82.3859, city:"Brooksville", url:"https://www.dawncenter.org", address:"Confidential location (Brooksville area) — call the hotline; pin shows city center only, not the shelter", phone:"24-Hour Hotline (352) 686-8430 · Admin (352) 684-7191", org:"SALVARE, Inc. d/b/a Dawn Center of Hernando County", verified:"2026-08-03", idRequired:"No ID and no documentation/proof of domestic violence required for admission — confirmed on independent DV-resource directories. Call the 24-hour hotline for a phone screening; that call is the entry point, not a document.", services:["shelter","dv","legal","casework"], notes:"24-hour staffed emergency shelter for survivors of domestic/sexual violence and their children — food, clothing, hygiene items, advocacy, crisis counseling, safety planning. The shelter's physical location is intentionally not published, for resident safety — call the hotline, do not try to locate the building." },

  // ---- FOOD PANTRIES / MEALS (not otherwise part of a hub above) ----
  { name:"Nature Coast Outreach Center (formerly Joseph's House)", category:"food", county:"Hernando", st:"FL", lat:28.54456, lng:-82.38313, city:"Brooksville", url:"https://www.naturecoastoutreach.org", address:"823 Josephine St, Brooksville, FL 34601", phone:"(352) 600-8295", org:"Nature Coast Outreach Center, Inc.", verified:"2026-08-03", services:["food","casework"], notes:"100% volunteer-run free food pantry and community outreach/drop-in point; some directories still list the org's former name, Joseph's House. Call to confirm current hours and whether crisis drop-in services are active." },
  { name:"Allen Temple AME Church", category:"food", county:"Hernando", st:"FL", lat:28.54452, lng:-82.38224, city:"Brooksville", url:"", address:"824 Leonard St, Brooksville, FL 34601", phone:"(352) 796-2597", when:"2nd & 4th Thurs, 9am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Brooksville First United Methodist Church", category:"food", county:"Hernando", st:"FL", lat:28.55488, lng:-82.38954, city:"Brooksville", url:"", address:"109 S Broad St, Brooksville, FL 34601", phone:"(352) 796-3363", when:"2nd & 4th Sat, 9–10am", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Christ Lutheran Church (Brooksville)", category:"food", county:"Hernando", st:"FL", lat:28.55527, lng:-82.38787, city:"Brooksville", url:"", address:"Brooksville, FL 34601 (exact street address not listed — call to confirm)", phone:"", when:"2nd/4th Wed 9–10am (breakfast); 3rd Wed dinner 4:30–6pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active; pin is approximate (Brooksville city center)." },
  { name:"Christ the King Full Gospel Worship", category:"food", county:"Hernando", st:"FL", lat:28.53139, lng:-82.58338, city:"Brooksville", url:"", address:"7138 Lykes St, Brooksville, FL 34613", phone:"(352) 596-5366", when:"Fri, 10–11:30am", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Christian Life Assembly of God", category:"food", county:"Hernando", st:"FL", lat:28.53718, lng:-82.51190, city:"Brooksville", url:"", address:"13065 Jacqueline Rd, Brooksville, FL 34613", phone:"(352) 597-1139", when:"Tues, 11am–1:30pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Day Star Life Center", category:"food", county:"Hernando", st:"FL", lat:28.53049, lng:-82.39369, city:"Brooksville", url:"", address:"7120 Hope Hill Rd, Brooksville, FL 34601", phone:"(352) 799-5930", when:"Thurs, 9am–12:30pm (bring ID)", services:["food"], notes:"Also runs the DayStar Life Center Thrift Shops (see Clothing) which fund this pantry. Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Fellowship Community Church", category:"food", county:"Hernando", st:"FL", lat:28.46162, lng:-82.53718, city:"Spring Hill", url:"", address:"11250 Spring Hill Dr, Spring Hill, FL 34609", phone:"(352) 686-4612", when:"2nd Wed, 10am–1pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"First Baptist Church of Spring Hill", category:"food", county:"Hernando", st:"FL", lat:28.44172, lng:-82.60385, city:"Spring Hill", url:"", address:"7279 Pinehurst Dr, Spring Hill, FL 34606", phone:"(352) 683-2863", when:"4th Tues, 9:30am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"First Presbyterian Church (Brooksville)", category:"food", county:"Hernando", st:"FL", lat:28.55801, lng:-82.38374, city:"Brooksville", url:"", address:"250 Bell Ave, Brooksville, FL 34601", phone:"(352) 796-4228", when:"2nd Thurs, 11am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Hillside Community Baptist Church", category:"food", county:"Hernando", st:"FL", lat:28.52306, lng:-82.28092, city:"Brooksville", url:"", address:"27440 Cortez Blvd, Brooksville, FL 34602", phone:"(352) 799-0687", when:"Call for appt — Wed 4–5:30pm & Sat 12–3pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Forest Oaks Lutheran Church", category:"food", county:"Hernando", st:"FL", lat:28.48769, lng:-82.57820, city:"Spring Hill", url:"", address:"8555 Forest Oaks Blvd, Spring Hill, FL 34606", phone:"(352) 683-9731", when:"Tues, 9am–noon (drive-thru, bring ID)", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Grace Presbyterian & St. Marks", category:"food", county:"Hernando", st:"FL", lat:28.45545, lng:-82.58044, city:"Spring Hill", url:"", address:"8375 Spring Hill Dr, Spring Hill, FL 34608", phone:"(352) 683-2082", when:"Tues, 9–11am", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Grace World Outreach Church", category:"food", county:"Hernando", st:"FL", lat:28.53843, lng:-82.39301, city:"Brooksville", url:"", address:"20366 Cortez Blvd, Brooksville, FL 34601", phone:"(352) 796-3685", when:"3rd Sat, 9–11am", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Greater Love Outreach Ministries", category:"food", county:"Hernando", st:"FL", lat:28.578, lng:-82.40298, city:"Brooksville", url:"", address:"20053 Yontz Rd, Brooksville, FL 34601", phone:"(352) 585-7328", when:"Tues & Thurs, 10am–1pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Holy Cross Lutheran Church", category:"food", county:"Hernando", st:"FL", lat:28.45589, lng:-82.61717, city:"Spring Hill", url:"", address:"6193 Spring Hill Dr, Spring Hill, FL 34606", phone:"(352) 683-9016", when:"Mon, 9:30am–12:30pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Holy Trinity Lutheran Church", category:"food", county:"Hernando", st:"FL", lat:28.45192, lng:-82.45169, city:"Masaryktown", url:"", address:"1214 Broad St, Masaryktown, FL 34604", phone:"(352) 796-4066", when:"Tues, 9–11:45am", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Life Church Spring Hill", category:"food", county:"Hernando", st:"FL", lat:28.43362, lng:-82.50373, city:"Spring Hill", url:"", address:"18924 County Line Rd, Spring Hill, FL 34610", phone:"(352) 799-2821", when:"Fri, 3–6pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Mariner United Methodist Church", category:"food", county:"Hernando", st:"FL", lat:28.52997, lng:-82.51163, city:"Spring Hill", url:"", address:"7079 Mariner Blvd, Spring Hill, FL 34609", phone:"(352) 596-0080", when:"Mon & Thurs, 9–11am (curbside)", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Nativity Lutheran Church", category:"food", county:"Hernando", st:"FL", lat:28.52387, lng:-82.57149, city:"Weeki Wachee", url:"", address:"6363 Commercial Way, Weeki Wachee, FL 34613", phone:"(352) 597-1456", when:"Wed & Thurs, 9:30am–1pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"New Hope Assembly of God", category:"food", county:"Hernando", st:"FL", lat:28.52307, lng:-82.27876, city:"Brooksville", url:"", address:"27488 Cortez Blvd, Brooksville, FL 34602", phone:"(352) 544-0786", when:"3rd Thurs, 9am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Northcliff Church", category:"food", county:"Hernando", st:"FL", lat:28.49411, lng:-82.54768, city:"Spring Hill", url:"", address:"10515 Northcliffe Blvd, Spring Hill, FL 34608", phone:"(352) 683-5882", when:"Tues 2–4pm, Thurs 10am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Providence Church", category:"food", county:"Hernando", st:"FL", lat:28.51395, lng:-82.51839, city:"Spring Hill", url:"", address:"6000 Mariner Blvd, Spring Hill, FL 34609", phone:"(352) 556-2490", when:"Fri, 10am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Ridge Manor United Methodist Church", category:"food", county:"Hernando", st:"FL", lat:28.50776, lng:-82.17573, city:"Ridge Manor", url:"", address:"34350 Cortez Blvd, Ridge Manor, FL 33523", phone:"(352) 583-3770", when:"1st & 3rd Mon, 4–5:30pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Spring Hill Calvary Church (Nazarene)", category:"food", county:"Hernando", st:"FL", lat:28.43572, lng:-82.60204, city:"Spring Hill", url:"", address:"235 Cobblestone Rd, Spring Hill, FL 34606", phone:"(352) 683-0587", when:"2nd & 4th Tues, 11am–1pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Spring Hill Seventh Day Adventist Church", category:"food", county:"Hernando", st:"FL", lat:28.46098, lng:-82.63631, city:"Spring Hill", url:"", address:"2300 Osowaw Blvd, Spring Hill, FL 34607", phone:"(352) 686-1143", when:"2nd & 4th Sun, 12–2pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Spring Life Church", category:"food", county:"Hernando", st:"FL", lat:28.45505, lng:-82.56506, city:"Spring Hill", url:"", address:"9344 Spring Hill Dr, Spring Hill, FL 34608", phone:"(352) 683-2600", when:"Wed, 9am–2pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Hernando County Family YMCA", category:"hub", county:"Hernando", st:"FL", lat:28.45368, lng:-82.5392, city:"Spring Hill", url:"https://www.ymcasuncoast.org/locations/hernando-county-branch", address:"1300 Mariner Blvd, Spring Hill, FL 34609", phone:"(352) 688-9622", org:"YMCA of the Suncoast", verified:"2026-08-03", services:["food","showers","financial"], notes:"Full-service YMCA with locker-room showers and a sliding-fee-scale Financial Assistance Program for membership (call to ask — everyone who qualifies gets some level of assistance based on fund availability). Also listed on PHP's countywide pantry sheet (dated Oct 2021, unconfirmed this sweep) as hosting a monthly food pantry, 1st Thurs 4:30pm — atypical for a YMCA branch, call to confirm it's still active. Hours: Mon–Thu 5am–9:30pm, Fri 5am–9pm, Sat 7am–6pm, Sun 11am–5pm." },
  { name:"Church of God of Prophecy — Firstfruits Food Pantry", category:"food", county:"Hernando", st:"FL", lat:28.53405, lng:-82.40727, city:"Brooksville", url:"", address:"15444 Wiscon Rd, Brooksville, FL 34601", phone:"(352) 345-1990 / (352) 345-2956", when:"Call for schedule", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Florida Food Force", category:"food", county:"Hillsborough", st:"FL", lat:28.19668, lng:-82.62453, city:"Odessa", url:"https://floridafoodforce.org", address:"11523 Prosperous Dr, Odessa, FL 33556", phone:"(727) 261-7422", org:"Florida Food Force, Inc.", verified:"2026-08-03", services:["food"], notes:"HQ is in Hillsborough County (not Hernando), but the weekly supplemental food program has no income or county restriction and reaches into the Nature Coast — worth calling. Office hours Mon–Wed 9am–3pm." },

  // ---- CLOTHING / THRIFT (voucher & free-goods programs) ----
  { name:"St. Vincent de Paul — Second Location (unconfirmed)", category:"clothing", county:"Hernando", st:"FL", lat:28.43132, lng:-82.46314, city:"Spring Hill", url:"", address:"18810 US-41, Spring Hill, FL", phone:"(352) 796-6606", org:"St. Vincent de Paul (SVDP)", notes:"Unclear whether this is a second store or a conference/casework office — call to confirm before visiting." },
  { name:"Salvation Army Family Store", category:"clothing", county:"Hernando", st:"FL", lat:28.48465, lng:-82.6052, city:"Spring Hill", url:"https://tampa.salvationarmyflorida.org", address:"3570 Commercial Way (US-19), Spring Hill, FL", phone:"(352) 666-9009", org:"The Salvation Army", verified:"2026-08-03", services:["clothing"], notes:"Emergency vouchers for free clothing/furniture/housewares are issued by a caseworker at the Hernando County Corps office (352-796-1186, now at 342 Beverly Court), not at the store counter — get the voucher first." },
  { name:"Goodwill Spring Hill Superstore", category:"clothing", county:"Hernando", st:"FL", lat:28.49703, lng:-82.59127, city:"Spring Hill", url:"", address:"4750 Commercial Way, Spring Hill, FL", phone:"(352) 596-1712", services:["clothing"], notes:"Standard low-cost thrift, not a voucher program — worth checking for periodic community giveaway events." },
  { name:"Jericho Road Thrift Store — County Line Rd", category:"clothing", county:"Hernando", st:"FL", lat:28.43377, lng:-82.56659, city:"Spring Hill", url:"https://www.jericho-road.net", address:"15000 County Line Rd, Spring Hill, FL", phone:"(352) 799-2912", org:"Jericho Road Ministries", services:["clothing"], notes:"Sales fund Jericho Road Ministries' shelter and recovery programs; ask about direct clothing help." },
  { name:"Jericho Road Thrift Store — Commercial Way", category:"clothing", county:"Hernando", st:"FL", lat:28.5043, lng:-82.58705, city:"Spring Hill", url:"https://www.jericho-road.net", address:"5260 Commercial Way, Spring Hill, FL", phone:"(352) 799-2912", org:"Jericho Road Ministries", services:["clothing"], notes:"Second Jericho Road Ministries thrift location; ask about direct clothing help." },
  { name:"DayStar Life Center Thrift Shops", category:"clothing", county:"Hernando", st:"FL", lat:28.53808, lng:-82.39138, city:"Brooksville", url:"", address:"20428 Cortez Blvd, Brooksville, FL", phone:"(352) 799-5930", org:"Day Star Life Center", services:["clothing"], notes:"Thrift sales fund DayStar's food pantry program (see Day Star Life Center under Food); also accepts donations." },

  // ---- PET FOOD ----
  { name:"Humane Society of the Nature Coast — Little Pet Pantry", category:"pet", county:"Hernando", st:"FL", lat:28.53398, lng:-82.42462, city:"Brooksville", url:"https://humanerescue.org", address:"7200 Mobley Rd, Brooksville, FL 34601", phone:"(352) 796-2711", org:"Humane Society of the Nature Coast", verified:"2026-08-03", services:["petfood"], notes:"Free self-serve pet food pantry just outside the shelter's main gate for Hernando County residents struggling to feed pets, first-come first-served — ask staff if it's empty. Shelter hours Mon–Tue & Thu–Sun 11am–5pm (closed Wed). Several human food pantries above also report occasional donated pet food — worth asking, especially at Feeding Tampa Bay mobile distributions." },

  // ---- TRANSPORTATION ----
  { name:"TheBus (Hernando County Transit) — Operations Office", category:"transportation", county:"Hernando", st:"FL", lat:28.54562, lng:-82.37694, city:"Brooksville", url:"https://www.hernandocounty.us", address:"700 Aeriform Dr, Brooksville, FL 34601", phone:"(352) 754-4444", org:"Hernando County Transit", email:"thebus@hernandocounty.us", verified:"2026-08-03", services:["transportation"], notes:"No dedicated homeless bus-voucher program listed publicly, but two reliable paths to free/reduced fares: (1) Reduced-Fare Photo ID for seniors 65+, students, and people with disabilities — form + ID at this office; (2) case-manager-issued bus passes — ask a PHP, Salvation Army, or Catholic Charities caseworker. Fares via the Token Transit app or cash on board; fare-capping auto-upgrades you to a cheaper pass type once you've paid enough in a day. Trans-Hernando door-to-door paratransit is run separately by Mid-Florida Community Services (see Hubs) — standard fare $5/$10 round trip, reduced by income/employment/veteran status ($1 each way for veterans and their families), reservations (352) 799-1510." },

  // ---- COORDINATING / ADVOCACY AGENCIES ----
  { name:"Mid Florida Homeless Coalition (Regional HQ — Continuum of Care Lead)", category:"coalition", county:"Citrus", st:"FL", lat:28.83582, lng:-82.33037, city:"Inverness", url:"https://midfloridahomeless.org", address:"1512 US-41, Inverness, FL 34450 (pin is Inverness city center — exact address didn't resolve on the geocoders used; street address is otherwise correct per the org's own site)", phone:"(352) 860-2308", org:"Mid Florida Homeless Coalition, Inc.", email:"info@midflhc.org", verified:"2026-08-03", services:["housing","casework"], notes:"HQ is in Citrus County, not Hernando, but this is the official HUD Continuum of Care lead agency for Citrus, Hernando, Lake, and Sumter counties — the entry point for coordinated-entry housing placement and diversion/wrap-around services. As of late-2025 reporting, MFHC's own leadership described Hernando County service capacity as \"pretty narrow in scope\" — meaning MFHC is the right place to call to get connected/assessed, but persistence and follow-up matter given limited local shelter capacity. Office hours Mon–Fri 8am–5pm." },
  { name:"Hernando Community Coalition (houses the Hernando Homeless Initiative)", category:"coalition", county:"Hernando", st:"FL", lat:28.4671, lng:-82.51121, city:"Spring Hill", url:"https://hernandocommunitycoalition.org", address:"13001 Spring Hill Dr, Spring Hill, FL 34609", phone:"(352) 596-8000", org:"Hernando Community Coalition", verified:"2026-08-03", services:["casework"], notes:"Countywide behavioral-health partnership; also the host organization for the Hernando Homeless Initiative (HHI, started ~2023) — a task force combining PHP, this Coalition, and other local nonprofits to coordinate transportation to services, sanitation partnerships with the county, and joint \"one-stop-shop\" events (legal aid, medical/dental/vet care, mobile showers, VA advocate services). Watch PHP's Facebook page or this org's site for HHI event dates; HHI contact is Tresa Watson via this office." },

  // ---- HOTLINES / CRISIS LINES ----
  { name:"211 / First Contact (Crisis & Referral Line)", category:"hotline", county:"Hernando", st:"FL", lat:28.5546, lng:-82.3903, city:"Brooksville", url:"https://www.firstcontact.org", address:"Phone/online service — no single physical address in Hernando County; pin shows Brooksville, the county seat", phone:"Dial 211 · (727) 562-1543 (cell-phone access)", org:"First Contact (formerly 211 Tampa Bay Cares)", verified:"2026-08-03", services:["casework","housing","food"], notes:"24/7, 100+ languages. The single best all-purpose number to call first if you're not sure where to start — operators can check real-time bed/pantry availability across Hernando County." },
  { name:"Bay Area Legal Services", category:"hotline", county:"Hernando", st:"FL", lat:28.5546, lng:-82.3903, city:"Brooksville", url:"https://www.bals.org", address:"Regional legal-aid nonprofit — no walk-in Hernando office found; pin shows Brooksville, the county seat", phone:"1-800-625-2257", org:"Bay Area Legal Services", verified:"2026-08-03", services:["legal","housing"], notes:"Free civil legal aid covering housing/eviction defense, family law, disability benefits, expungement, and consumer matters — the resource to call before an eviction hearing or over a denied benefits claim." },
  { name:"Veterans Crisis Line", category:"hotline", county:"Hernando", st:"FL", lat:28.5546, lng:-82.3903, city:"Brooksville", url:"https://www.veteranscrisisline.net", address:"National 24/7 hotline — no physical location; pin shows Brooksville, the county seat", phone:"988 then press 1 · text 838255", org:"US Dept. of Veterans Affairs", verified:"2026-08-03", services:["veterans","mentalhealth"], notes:"24/7 crisis support for veterans and their families, confidential, staffed by responders with military culture training." },
  { name:"United Way of Hernando County", category:"coalition", county:"Hernando", st:"FL", lat:28.48796, lng:-82.60216, city:"Spring Hill", url:"https://www.unitedwayhernando.org", address:"4028 Commercial Way, Spring Hill, FL 34606", phone:"(352) 688-2026", org:"United Way of Hernando County", verified:"2026-08-03", services:["casework","housing","food"], notes:"Central referral hub distinct from 211 — funds and coordinates local programs across food, housing, legal, healthcare, disaster relief, mental health, veterans, and senior services countywide. Mon–Fri 9am–5pm." },

  // ---- MENTAL HEALTH & VETERAN SUPPORT ----
  { name:"NAMI Hernando", category:"medical", county:"Hernando", st:"FL", lat:28.48797, lng:-82.60215, city:"Spring Hill", url:"https://namihernando.org", address:"4030 Commercial Way, Spring Hill, FL 34606", phone:"(352) 684-0004", org:"National Alliance on Mental Illness — Hernando affiliate", email:"hope@namihernando.org", verified:"2026-08-03", services:["mentalhealth","casework"], notes:"Free peer support, family support groups, and mental-health education — six support groups running weekly, with tracks for veterans, teens, and caregivers. Also distributes cold-weather supplies (gloves, hand warmers, blankets) in winter. Mon–Fri 9am–5pm." },
  { name:"Pathways Counseling Center", category:"medical", county:"Hernando", st:"FL", lat:28.4779, lng:-82.61130, city:"Spring Hill", url:"https://pathwayscounselingcenter.net", address:"3261 Commercial Way, Spring Hill, FL 34606", phone:"(352) 686-3188", org:"Pathways Counseling Center", verified:"2026-08-03", services:["mentalhealth"], notes:"Outpatient counseling. Mon–Thu 9am–7pm, Fri 9am–5pm, closed weekends." },
  { name:"K9 Partners for Patriots", category:"medical", county:"Hernando", st:"FL", lat:28.47954, lng:-82.47563, city:"Brooksville", url:"https://k9partnersforpatriots.com", address:"15322 Aviation Loop Dr, Brooksville, FL 34604", phone:"(352) 397-5306", org:"K9 Partners for Patriots, Inc.", email:"info@k9partnersforpatriots.com", verified:"2026-08-03", services:["veterans","mentalhealth"], notes:"Trains and provides service dogs for veterans with PTSD, alongside veteran support counseling — free to qualifying veterans." },
  { name:"Veterans' HEAT Factory", category:"medical", county:"Hernando", st:"FL", lat:28.48046, lng:-82.45976, city:"Brooksville", url:"https://veteransheatfactory.com", address:"16230 Aviation Loop Dr, Brooksville, FL 34604", phone:"(352) 251-7015", org:"Veterans H.E.A.T. Factory, Inc.", verified:"2026-08-03", services:["veterans","mentalhealth"], notes:"PTSD recovery and reintegration support for veterans. Hours 10am–4pm." },
  { name:"Premier Community HealthCare — Spring Hill Family Health Center", category:"medical", county:"Hernando", st:"FL", lat:28.49107, lng:-82.59091, city:"Spring Hill", url:"https://premierhc.org/locations/spring-hill-family-health-center/", address:"7551 Forest Oaks Blvd, Spring Hill, FL 34606", phone:"(352) 518-2000", org:"Premier Community HealthCare (FQHC)", verified:"2026-08-03", services:["medical","mentalhealth"], notes:"Federally Qualified Health Center — sliding-scale fees for self-pay patients, accepts Medicaid, primary care plus behavioral health services. Also a Florida Dept. of Health WIC office at this address, Mon–Fri 8am–5pm (Tue to 6pm). Mon 7am–7pm, Tue–Fri 7am–4pm." },
  { name:"Premier Community HealthCare — Brooksville Family Health Center", category:"medical", county:"Hernando", st:"FL", lat:28.55207, lng:-82.38797, city:"Brooksville", url:"https://premierhc.org/locations/brooksville-family-health-center/", address:"300 S Main St, Brooksville, FL 34601", phone:"(352) 518-2000", org:"Premier Community HealthCare (FQHC)", verified:"2026-08-03", services:["medical","mentalhealth"], notes:"Same sliding-scale/Medicaid model as the Spring Hill location. Also a Florida Dept. of Health WIC office at this address, Tue/Wed/Fri 8am–5pm. Mon 7am–7pm, Tue–Fri 7am–4pm." },

  // ---- ADDITIONAL SHELTER (found in the second research pass) ----
  { name:"New Beginnings Youth Shelter (ages 10–17)", category:"shelter", county:"Hernando", st:"FL", lat:28.5546, lng:-82.3903, city:"Brooksville", url:"https://yfainc.org/hernando", address:"Confidential-in-practice — a published street address (Sheriff Mylander Way, Brooksville) would not resolve on two independent geocoders, so this pin is a generalized Brooksville city-center point rather than risk a wrong location for a minors' shelter", phone:"(352) 540-6015", org:"Youth & Family Alternatives (YFA), Inc.", verified:"2026-08-03", idRequired:"No ID requirement found or expected — this shelter exists specifically for minors in crisis, who often arrive with no documents at all. Typical entry paths for this kind of DJJ-affiliated youth shelter are a call to the shelter's own line, law enforcement, DCF, or a school counselor/crisis line referral, though the exact intake mechanics weren't independently confirmed on the org's own materials for this pass — call the number here first. Explicitly NOT accepted per published eligibility: youth who are violent, on juvenile probation, suicidal, psychotic, intoxicated, or on drugs — those situations need a different (medical/crisis) response.", services:["shelter","children","legal","dv"], notes:"24/7/365 emergency shelter for youth ages 10–17 who are runaway, homeless, locked out, or need crisis placement due to abuse/neglect/trauma. Free. Serves Hernando, Sumter, and Citrus counties. Call first — this is a crisis intake line, not a walk-in." },
  { name:"Esther's House (REbuilt Recovery Program, women)", category:"shelter", county:"Hernando", st:"FL", lat:28.52905, lng:-82.40907, city:"Brooksville", url:"https://www.jericho-road.net/recovery", address:"19384 Ingram St, Brooksville, FL 34601", phone:"(352) 799-2912 ext 308", org:"Jericho Road Ministries", verified:"2026-08-03", idRequired:"No photo-ID requirement published. Same real gate as Joshua's House: 18+, already medically detoxed, willing to commit to the 5-month minimum program, passes a phone pre-screening interview.", services:["shelter"], notes:"30-bed women's residential facility for Jericho Road's REbuilt recovery program (5-to-25 months) — this is confirmed by name on the org's own current site as one of its two residential centers, opened 2025. Distinct from (and much longer-term than) Mary's House's up-to-3-day emergency shelter above. Apply the same way as Joshua's House: Recovery Program Request form → phone pre-screening → notification. Free. CONFIDENCE NOTE: extension 308 comes from a single directory source, not independently corroborated — the main line (352) 799-2912 is solidly confirmed, so start there and ask for Esther's House if the extension doesn't connect." },
  { name:"The Life Center of Hernando", category:"shelter", county:"Hernando", st:"FL", lat:28.5546, lng:-82.3903, city:"Brooksville", url:"https://www.lifecenterofhernando.com", address:"Confidential residential program — no street address published by the org itself; pin shows Brooksville, the county seat", phone:"(352) 597-0119", org:"The Life Center of Hernando", email:"thelifecenterfl@gmail.com", verified:"2026-08-03", idRequired:"No photo-ID requirement published. The actual gate is an eligibility phone pre-screening, not a document: must be 18–25, unmarried/separated (or emancipated), pregnant or have custody of a child under 5, drug-free including tobacco/alcohol BEFORE admission, and have no serious diagnosed violent/aggression behavior problems. Call to complete a pre-screening form over the phone — that call is the application.", services:["shelter","children"], notes:"Long-term transitional housing (not emergency shelter) for up to 8 young mothers, ages 18–25, and their preschool children at risk of homelessness — time to give birth, finish school, and become employed. Priority given to pregnant applicants and mothers with children under 5. Some third-party directories list a street address for this org; it is deliberately omitted here because the org's own site does not publish one." },
  { name:"Hernando County Warming Center (seasonal, cold-weather nights only)", category:"shelter", county:"Hernando", st:"FL", lat:28.54882, lng:-82.39889, city:"Brooksville", url:"https://www.hernandocounty.us", address:"The Enrichment Center, 800 John Gary Grubbs Blvd, Brooksville, FL 34601", phone:"(352) 540-4338", org:"Hernando County Emergency Management + City of Brooksville", verified:"2026-08-03", idRequired:"No ID or documentation requirement found in any of the county's own opening-night press releases — every announcement checked simply describes it as open \"to those in need,\" with no eligibility criteria or ID mentioned at all. Appears to be the lowest-barrier shelter option on this map — but it's also the most limited (overnight only, weather-triggered, no meals/cots, pets not accepted).", services:["shelter"], notes:"Opens only on cold-weather nights (announced ad hoc via county news releases) — 8pm to 8am, no meals or cots provided, pets not accepted. Free TheBus transport: pickup 8pm at the Walmart, 7305 Broad St, Brooksville, return drop-off 8am same spot. Call county HHS or watch hernandocounty.us news for open/close announcements." },

  // ---- WORKSPACE (free computers, job search, meeting rooms) ----
  { name:"CareerSource Pasco Hernando — Brooksville Center", category:"workspace", county:"Hernando", st:"FL", lat:28.54105, lng:-82.45651, city:"Brooksville", url:"https://careersourcepascohernando.com", address:"16336 Cortez Blvd, Brooksville, FL 34601", phone:"(352) 200-3020", org:"CareerSource Pasco Hernando", verified:"2026-08-03", services:["workspace","casework"], notes:"Free American Job Center — computers with internet for job search and resume building, career counseling, skills workshops, hiring events, and training funds for those eligible. No cost, no appointment required for basic services. Mon–Fri 8am–5pm." },
  { name:"Hernando County Public Library — Main Branch", category:"workspace", county:"Hernando", st:"FL", lat:28.55688, lng:-82.38727, city:"Brooksville", url:"https://hernandocountylibrary.us", address:"238 Howell Ave, Brooksville, FL 34601", phone:"(352) 754-4043", org:"Hernando County Public Library System", verified:"2026-08-03", services:["workspace"], notes:"Free computers and high-speed internet — no library card required. Meeting rooms bookable for individual or nonprofit-group use during open hours. Mon–Wed 10am–6pm, Thu 12–8pm, Fri 9am–5pm, closed Sat–Sun." },
  { name:"Hernando County Public Library — East Hernando Branch", category:"workspace", county:"Hernando", st:"FL", lat:28.5283, lng:-82.23357, city:"Brooksville", url:"https://hernandocountylibrary.us", address:"6457 Windmere Rd, Brooksville, FL 34602", phone:"", org:"Hernando County Public Library System", verified:"2026-08-03", services:["workspace"], notes:"Free computers, no card required; bookable meeting room. Tue–Wed 10am–6pm, Thu 12–8pm, Fri–Sat 9am–5pm, closed Sun–Mon." },
  { name:"Hernando County Public Library — West Hernando Branch (temporarily closed)", category:"workspace", county:"Hernando", st:"FL", lat:28.52218, lng:-82.56435, city:"Brooksville", url:"https://hernandocountylibrary.us", address:"6335 Blackbird Ave, Brooksville, FL 34613", phone:"", org:"Hernando County Public Library System", verified:"2026-08-03", services:["workspace"], notes:"CLOSED for repairs starting May 11, 2026 — call the system or check hernandocountylibrary.us before visiting; normally free computers/no card required plus a bookable meeting room, Mon–Wed 10am–6pm, Thu 12–8pm, Fri 9am–5pm." },
  { name:"Hernando County Public Library — Spring Hill Branch (Harold G. Zopp Memorial)", category:"workspace", county:"Hernando", st:"FL", lat:28.45527, lng:-82.56894, city:"Spring Hill", url:"https://hernandocountylibrary.us", address:"9220 Spring Hill Dr, Spring Hill, FL 34608", phone:"", org:"Hernando County Public Library System", verified:"2026-08-03", services:["workspace"], notes:"Free computers, no card required; bookable meeting room. Tue–Wed 10am–6pm, Thu 12–8pm, Fri–Sat 9am–5pm, closed Sun–Mon." },

  // ---- HYGIENE (shower access — cheapest gym membership found, plus notes on free options above) ----
  { name:"Planet Fitness — Spring Hill", category:"hygiene", county:"Hernando", st:"FL", lat:28.4617, lng:-82.53914, city:"Spring Hill", url:"https://www.planetfitness.com/gyms/spring-hill-fl", address:"11156 Spring Hill Dr, Spring Hill, FL 34609", phone:"", org:"Planet Fitness", verified:"2026-08-03", services:["showers"], notes:"Cheapest confirmed gym membership in the county for shower access: Classic membership around $15/month (historically advertised as low as $10/mo — call/check current promo) plus a $49/yr annual fee, no long-term commitment, billed monthly. Locker rooms with showers standard at Planet Fitness. Free showers without a membership: PHP's HELP Center, Tue & Fri 10am–1pm (see Hubs)." },
  { name:"Anytime Fitness — Brooksville", category:"hygiene", county:"Hernando", st:"FL", lat:28.54121, lng:-82.40791, city:"Brooksville", url:"https://www.anytimefitness.com/locations/brooksville-florida-2183", address:"19340 Cortez Blvd, Brooksville, FL 34601", phone:"(352) 397-4862", org:"Anytime Fitness", verified:"2026-08-03", services:["showers"], notes:"24-hour access, private showers confirmed as an amenity. Membership pricing isn't posted publicly (franchise-set, industry average ~$30–50/mo) — call ahead; usually cheaper than a corporate chain if you negotiate month-to-month." },
  { name:"Anytime Fitness — Ridge Manor", category:"hygiene", county:"Hernando", st:"FL", lat:28.52297, lng:-82.2275, city:"Brooksville", url:"https://www.anytimefitness.com/locations/brooksville-florida-4644/", address:"31182 Cortez Blvd, Brooksville, FL 34602", phone:"", org:"Anytime Fitness", verified:"2026-08-03", services:["showers"], notes:"24-hour access; a separate franchise location from the Brooksville/Cortez club above, serving the Ridge Manor side of the county. Call for current membership pricing." },

  // ---- CAMPING (legally designated public camping only — see category
  //      note above; this is NOT a claim that any other public land in
  //      the county is open to overnight stays) ----
  { name:"Withlacoochee State Forest Visitor Center (permits & info)", category:"workspace", county:"Hernando", st:"FL", lat:28.63778, lng:-82.33962, city:"Brooksville", url:"https://www.fdacs.gov/Forest-Wildfire/Our-Forests/State-Forests/Withlacoochee-State-Forest", address:"15003 Broad St, Brooksville, FL 34601-4201", phone:"(352) 797-4140", org:"Florida Dept. of Agriculture & Consumer Services — Florida Forest Service", verified:"2026-08-03", services:["workspace"], notes:"Start here before camping anywhere on the Croom Tract below — this office issues the State Forest Use Authorization required for any organized/group activity, including a group of 6+ people camping. Solo/small-group primitive camping in the designated zones doesn't need a permit, but calling first confirms current conditions (burn bans, closures). Mon–Fri 8am–noon & 1–4:30pm, closed holidays." },
  { name:"Silver Lake Campground (Withlacoochee State Forest, Croom Tract)", category:"camping", county:"Hernando", st:"FL", lat:28.57361, lng:-82.22222, city:"Brooksville", url:"https://floridastateforests.reserveamerica.com/camping/silver-lake-campground-withlacoochee-state-forest/", address:"31475 Silver Lake Road, Brooksville, FL 34602", phone:"(352) 797-4140", org:"Florida Forest Service", verified:"2026-08-03", when:"Day-use gate: 8am–8pm. Registered campers get an after-hours gate code on their reservation confirmation, so a paid overnight stay isn't cut off by the day-use closing time — this is the one camping entry on this map where that's actually confirmed, not just assumed.", services:["showers"], notes:"Developed campground, 23 sites, $13.45/night (RV or tent) — full water/electric (30 & 50 amp) hookups at every site, a bathhouse with real showers, dump station, boat ramp, and Withlacoochee State Trail access. 3 sites (19–21) have enhanced accessibility. Reserve via ReserveAmerica (1-877-879-3859) or call the Visitor Center — cheapest legal, amenity-having overnight option in the county's public land system, and the shower access alone makes it worth knowing about even without an overnight stay in mind. DIRECTIONS: same general area as the Croom Tract primitive zones — via I-75 Exit 301, east on SR-50/US-98, north on Croom-Rital Rd; via Suncoast Parkway (589), north to SR-50, east through Brooksville, north on US-41 to Croom Rd (CR-480), then follow signage to Silver Lake Road." },
  { name:"Croom Tract Primitive Camp Zone East (free, hike-in)", category:"camping", county:"Hernando", st:"FL", lat:28.59667, lng:-82.23861, city:"Brooksville", url:"https://floridastateforests.reserveamerica.com/camping/croom-tract-primitive-camp-zone-east/", address:"Trailhead: Tucker Hill Trailhead, 26578 Croom Rd, Brooksville, FL 34601 — camp zone is a ~0.5 mile hike in from the parking area, marked by yellow bands on trees", phone:"(352) 797-4140", org:"Florida Forest Service", verified:"2026-08-03", when:"Day-use/trailhead parking: sunrise–sunset (statewide Florida Forest Service policy) — overnight camping itself is the sanctioned exception to that, but it wasn't possible to independently confirm whether the Tucker Hill parking area's vehicle gate physically locks at sunset. Call the Visitor Center (352-797-4140) before an overnight hike-in to make sure your car won't be locked in/out.", services:[], notes:"No camping fee for a solo camper or small group (Authorization only required for groups of 6+ — see Visitor Center entry); a separate $2/person day-use entrance fee (or $45 annual day-use pass) may apply just to park at the Tucker Hill trailhead regardless of camping — unconfirmed whether that's waived for registered overnight campers, ask when you call. Hike-in/hike-out only — no vehicle access to the camp zone itself. No water, no restrooms, no amenities beyond occasional fire rings/picnic tables at existing sites. Only cooking fires permitted. This is the more accessible of the two primitive zones (0.5 mi vs. 5.25 mi hike). DIRECTIONS to Tucker Hill Trailhead — via I-75: Exit 301, head east on SR-50/US-98, turn north on Croom-Rital Rd, continue ~8.5 miles. Via Suncoast Parkway (589): take it north to SR-50, head east through Brooksville, then north on US-41 (Broad St) to Croom Rd (CR-480), turn right/east ~5 miles to the trailhead." },
  { name:"Croom Tract Primitive Camp Zone West (free, hike-in)", category:"camping", county:"Hernando", st:"FL", lat:28.59833, lng:-82.29611, city:"Brooksville", url:"https://floridastateforests.reserveamerica.com/camping/croom-tract-primitive-camp-zone-west/", address:"Trailhead: Tucker Hill Trailhead, 26578 Croom Rd, Brooksville, FL 34601 — camp zone is a ~5.25 mile hike in from the parking area", phone:"(352) 797-4140", org:"Florida Forest Service", verified:"2026-08-03", when:"Day-use/trailhead parking: sunrise–sunset (statewide Florida Forest Service policy) — same unconfirmed gate-locking caveat as the East zone entry; call ahead.", services:[], notes:"Same free-camping/permit rules and possible $2/person day-use parking fee as the East zone, but a much longer hike in (5.25 miles) — realistically only workable with backpacking gear. No water, no amenities. Only cooking fires permitted. Same DIRECTIONS to Tucker Hill Trailhead as the East zone entry (shared trailhead) — via I-75: Exit 301, head east on SR-50/US-98, turn north on Croom-Rital Rd, continue ~8.5 miles. Via Suncoast Parkway (589): take it north to SR-50, head east through Brooksville, then north on US-41 (Broad St) to Croom Rd (CR-480), turn right/east ~5 miles to the trailhead." },
  { name:"Chassahowitzka River Campground (out of county, nearby)", category:"camping", county:"Citrus", st:"FL", lat:28.72333, lng:-82.60333, city:"Chassahowitzka", url:"https://chassahowitzkaflorida.com", address:"8600 W Miss Maggie Dr, Chassahowitzka, FL 34448", phone:"(352) 382-2200", org:"Citrus County Parks & Recreation", notes:"Just across the Citrus County line, included because it's the nearest fee campground to the parts of Hernando County where the WMA itself (Chassahowitzka Wildlife Management Area, overnight camping NOT permitted there) is the closest public land. 53 full-hookup RV sites plus 28 primitive tent sites, boat ramp, general store. Call for current nightly rates — not listed publicly." }
];
