/* =====================================================================
   DATA — this is the part you own. Edit this file only; index.html
   never needs to change when you add, remove, or fix a resource.

   This map starts scoped to Hernando County, FL, but the schema is built
   to grow — statewide, then national — the same way the cyber resource
   maps did. That's why every row carries `county` and `st` even though
   today they're all "Hernando" / "FL": it's what a future regions.js /
   state drill-down would key off, without ever touching this file's shape.

   How to add a row:
     1. Get lat/lng from a real geocoder (US Census Bureau geocoder —
        geocoding.geo.census.gov — or Nominatim/OpenStreetMap) or by
        right-clicking the spot in Google Maps. NEVER estimate/eyeball a
        coordinate for a resource a homeless or at-risk person might
        actually try to walk or ride a bus to — a wrong pin sends someone
        to the wrong building. Exception: confidential shelter locations
        (domestic-violence shelters) — see Dawn Center below — where the
        pin is deliberately generalized to the city center for safety and
        the notes say so explicitly.
     2. category — one of:
          hub      multi-service anchor (3+ distinct aid types under one
                    roof/org — food + medical + casework, etc.)
          food     food pantries, meal programs, mobile food distribution
          shelter  emergency/transitional shelter, domestic-violence
                    shelter — anywhere with actual overnight beds
          clothing thrift stores / free-clothing & household-goods
                    voucher programs
          medical  free/low-cost clinics
          coalition coordinating/advocacy agencies (CoC lead, task forces)
          transportation bus/paratransit systems
          pet      pet food pantries
          hotline  phone-first intake/crisis lines with no single
                    physical address people visit
     3. county / st — "Hernando" / "FL" today; keep populated on every
        row so a future statewide pass can filter/group by it immediately.
     4. url / address / phone / when / org may be "" or omitted if
        unknown — the popup simply omits empty fields. Never guess
        contact details.
     5. services: [...] — OPTIONAL, cross-cutting need tags, independent
        of category (same idea as the cyber map's `topics`). Fixed
        taxonomy: food, shelter, medical, clothing, financial,
        transportation, petfood, snap, veterans, seniors, children,
        casework, legal, dv (domestic violence), housing, energy
        (utility assistance), headstart. Only tag what's actually
        confirmed offered — don't guess.
     6. events: [{ title, when, topics:[] }] — OPTIONAL, named programs run
        out of one location on their own schedule (e.g. PHP's Neighborhood
        Blessings vs. its Tuesday medical clinic). Pulled only from the
        org's own published info, never invented.
     7. verified: "YYYY-MM-DD" — OPTIONAL, date this specific row was
        independently confirmed via the org's own site/a fresh search
        (not just carried over from an older compiled list). Rows without
        it should carry a call-ahead caveat in notes instead.

   Data sweep: August 2026. The county's own pantry-sheet source (compiled
   by People Helping People) is dated October 2021 — every church/pantry
   row sourced ONLY from that sheet says so in its notes and has no
   `verified` date. Call ahead before a special trip; volunteer-run
   pantry schedules drift as churches change staff. Anchor orgs (PHP,
   Mid-Florida Community Services/You Thrive, Catholic Charities, SVDP,
   Salvation Army, Jericho Road Ministries, Dawn Center, Hernando
   Community Coalition, Mid Florida Homeless Coalition, Humane Society of
   the Nature Coast, Nature Coast Outreach Center) were independently
   re-searched this sweep and carry a `verified` date.
   ===================================================================== */
const RESOURCES = [

  // ---- MULTI-SERVICE HUBS ----
  { name:"People Helping People (PHP) — Kass Circle HELP Center", category:"hub", county:"Hernando", st:"FL", lat:28.45322, lng:-82.59450, city:"Spring Hill", url:"https://www.phphernando.org", address:"1396 Kass Circle, Spring Hill, FL 34606", phone:"(352) 686-4466", org:"People Helping People in Hernando County, Inc.", verified:"2026-08-03", services:["food","medical","casework","snap","shelter"], notes:"Hernando County's only community resource/HELP Center — hot meals, showers, hygiene items, camping supplies for the unsheltered, free Wi-Fi. Two directory listings disagree slightly on general office hours (one says Tue/Fri 10am–2pm only) vs. the program-specific times below — call to confirm before a special trip. Email admin@phphernando.org.", events:[
    { title:"Neighborhood Blessings (hot meals, showers, hygiene, camping supplies)", when:"Tue & Fri lunch 11:30am–12:30pm; Sunday hot meal 3:30–4:30pm" },
    { title:"PHP Health Clinic (free medical, uninsured Hernando residents)", when:"Tuesdays, 10am–1pm" },
    { title:"Mobile Food Distribution (drive-through, w/ Feeding Tampa Bay)", when:"Last Wednesday of each month, ~9am–1pm (cars start moving ~10:30am)" },
    { title:"Weekend Blessings (kid-friendly weekend food backpacks)", when:"Ongoing during school year" },
    { title:"Senior Blessings (monthly supplemental grocery bags)", when:"Monthly" },
    { title:"SNAP application help", when:"By appointment — call to schedule" }
  ]},
  { name:"Mid-Florida Community Services — You Thrive Florida (Hernando HQ)", category:"hub", county:"Hernando", st:"FL", lat:28.54516, lng:-82.37345, city:"Brooksville", url:"https://youthrivefl.org/location/hernando-county/", address:"820 Kennedy Blvd, Brooksville, FL 34601", phone:"(352) 796-1425", org:"Mid-Florida Community Services, Inc.", verified:"2026-08-03", services:["transportation","seniors","children","energy","housing","headstart"], notes:"Runs Trans-Hernando paratransit (see Transportation below), Head Start, Senior Services, the Weatherization Assistance Program, the Children's Advocacy Center, and House to Home. Statewide info line 1-888-802-7483.", events:[
    { title:"Head Start", when:"(352) 754-2464" },
    { title:"Children's Advocacy Center", when:"(352) 754-8809" },
    { title:"Trans-Hernando paratransit reservations", when:"(352) 799-1510, by noon the business day prior" },
    { title:"Senior Services", when:"(352) 796-1426" },
    { title:"Weatherization Assistance Program", when:"(352) 796-1427" }
  ]},
  { name:"Catholic Charities, Diocese of St. Petersburg — Hernando Office", category:"hub", county:"Hernando", st:"FL", lat:28.48733, lng:-82.58198, city:"Spring Hill", url:"https://www.ccdosp.org", address:"8370 Forest Oaks Blvd, Spring Hill, FL 34606", phone:"(352) 686-9897", org:"Catholic Charities, Diocese of St. Petersburg", verified:"2026-08-03", services:["financial","housing","casework"], notes:"Mon–Fri 8am–5pm. Emergency financial/rent/utility assistance, Pathways rapid rehousing, housing counseling, immigration services, Foundations of Life pregnancy/parenting support, and the St. Teresa Apartments (Shelters of Hope) — one-bedroom affordable housing for low-income Hernando County residents. Availability of any given program varies — call to ask what's currently active. Their larger regional shelters (Pinellas Hope, Pasco Women's Shelter) are outside Hernando County but reachable through casework referral." },
  { name:"St. Vincent de Paul — Hernando/Citrus District Thrift Store & Food Pantry", category:"hub", county:"Hernando", st:"FL", lat:28.45339, lng:-82.59627, city:"Spring Hill", url:"", address:"1291 Kass Circle, Spring Hill, FL 34606", phone:"(352) 688-3331", org:"St. Vincent de Paul (SVDP)", verified:"2026-08-03", services:["clothing","food","casework"], notes:"Store hours Mon–Thurs 9am–4pm, Fri 8am–4pm, Sat 9am–1pm (closed Sun). Food pantry drive-thru Tues–Sat 9am–2pm. Free clothing/household vouchers for people in real need are issued through parish-based \"Conference\" casework (e.g. St. Theresa Conference, (352) 688-9997) — call ahead and ask to connect with a home visit/voucher rather than just walking in." },
  { name:"Salvation Army — Brooksville Office & Food Pantry", category:"hub", county:"Hernando", st:"FL", lat:28.53759, lng:-82.46926, city:"Brooksville", url:"https://tampa.salvationarmyflorida.org", address:"15464 Cortez Blvd, Brooksville, FL 34601", phone:"(352) 796-1186", org:"The Salvation Army", verified:"2026-08-03", services:["food","clothing","financial","casework"], notes:"Food pantry Tue 9–11am; pastries Mon/Thu/Fri 9am–12pm. Caseworkers here can help with SNAP, housing referrals, and can issue emergency vouchers for free clothing/furniture/housewares redeemable at the Family Store — ask about voucher eligibility before going to the store." },
  { name:"Hernando County Health & Human Services", category:"hub", county:"Hernando", st:"FL", lat:28.55555, lng:-82.39306, city:"Brooksville", url:"https://www.hernandocounty.us/living-here/housing-supportive-services/health-and-human-services", address:"621 W Jefferson St, Brooksville, FL 34601", phone:"(352) 540-4338", org:"Hernando County Government", verified:"2026-08-03", services:["snap","financial","casework","housing"], notes:"General county intake point for WIC vouchers, SNAP outreach, utility/rent assistance, ACCESS Florida benefits connections, and Meals on Wheels referrals." },

  // ---- SHELTER (real overnight beds) ----
  { name:"Jericho Road Ministries — Men's Shelter (Mondon Hill)", category:"shelter", county:"Hernando", st:"FL", lat:28.55647, lng:-82.37537, city:"Brooksville", url:"https://www.jericho-road.net", address:"1090 Mondon Hill Rd, Brooksville, FL", phone:"(352) 799-2912", org:"Jericho Road Ministries", verified:"2026-08-03", services:["shelter","food"], notes:"Emergency daily shelter for homeless men — ~14 beds, meals and clothing, entry point to the New Life recovery program." },
  { name:"Jericho Road Ministries — Mary's House (Women's Shelter) & Jericho Food Barn", category:"shelter", county:"Hernando", st:"FL", lat:28.57268, lng:-82.37867, city:"Brooksville", url:"https://www.jericho-road.net", address:"1163 Howell Ave, Brooksville, FL 34601", phone:"(352) 799-2912 ext 112", org:"Jericho Road Ministries", verified:"2026-08-03", services:["shelter","food"], notes:"Mary's House — 6-bed emergency shelter for single women. The Jericho Food Barn pantry runs from the same campus, Tues & Fri 9am–noon (must have Hernando Co. ID)." },
  { name:"Jericho Road Ministries — Joshua House", category:"shelter", county:"Hernando", st:"FL", lat:28.56544, lng:-82.37551, city:"Brooksville", url:"https://www.jericho-road.net", address:"11014 Broad St, Brooksville, FL", phone:"(352) 799-2912", org:"Jericho Road Ministries", verified:"2026-08-03", services:["shelter"], notes:"Men's education center and shelter, ~30 beds — a remodeled former church funded by a $400,000 grant." },
  { name:"Dawn Center of Hernando County — Domestic Violence Emergency Shelter", category:"shelter", county:"Hernando", st:"FL", lat:28.5544, lng:-82.3859, city:"Brooksville", url:"https://www.dawncenter.org", address:"Confidential location (Brooksville area) — call the hotline; pin shows city center only, not the shelter", phone:"24-Hour Hotline (352) 686-8430 · Admin (352) 684-7191", org:"SALVARE, Inc. d/b/a Dawn Center of Hernando County", verified:"2026-08-03", services:["shelter","dv","legal","casework"], notes:"24-hour staffed emergency shelter for survivors of domestic/sexual violence and their children — food, clothing, hygiene items, advocacy, crisis counseling, safety planning. The shelter's physical location is intentionally not published, for resident safety — call the hotline, do not try to locate the building." },

  // ---- FOOD PANTRIES / MEALS (not otherwise part of a hub above) ----
  { name:"Nature Coast Outreach Center (formerly Joseph's House)", category:"food", county:"Hernando", st:"FL", lat:28.54456, lng:-82.38313, city:"Brooksville", url:"https://www.naturecoastoutreach.org", address:"823 Josephine St, Brooksville, FL 34601", phone:"(352) 600-8295", org:"Nature Coast Outreach Center, Inc.", verified:"2026-08-03", services:["food","casework"], notes:"100% volunteer-run free food pantry and community outreach/drop-in point; some directories still list the org's former name, Joseph's House. Call to confirm current hours and whether crisis drop-in services are active." },
  { name:"Allen Temple AME Church", category:"food", county:"Hernando", st:"FL", lat:28.54452, lng:-82.38224, city:"Brooksville", url:"", address:"824 Leonard St, Brooksville, FL 34601", phone:"(352) 796-2597", when:"2nd & 4th Thurs, 9am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Brooksville First United Methodist Church", category:"food", county:"Hernando", st:"FL", lat:28.55488, lng:-82.38954, city:"Brooksville", url:"", address:"109 S Broad St, Brooksville, FL 34601", phone:"(352) 796-3363", when:"2nd & 4th Sat, 9–10am", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Christ Lutheran Church (Brooksville)", category:"food", county:"Hernando", st:"FL", lat:28.55527, lng:-82.38787, city:"Brooksville", url:"", address:"Brooksville, FL 34601 (exact street address not listed — call to confirm)", phone:"", when:"2nd/4th Wed 9–10am (breakfast); 3rd Wed dinner 4:30–6pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active; pin is approximate (Brooksville city center)." },
  { name:"Christ the King Full Gospel Worship", category:"food", county:"Hernando", st:"FL", lat:28.53139, lng:-82.58338, city:"Brooksville", url:"", address:"7138 Lykes St, Brooksville, FL 34613", phone:"(352) 596-5366", when:"Fri, 10–11:30am", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Christian Life Assembly of God", category:"food", county:"Hernando", st:"FL", lat:28.53718, lng:-82.51190, city:"Brooksville", url:"", address:"13065 Jacqueline Rd, Brooksville, FL 34613", phone:"(352) 597-1139", when:"Tues, 11am–1:30pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Day Star Life Center", category:"food", county:"Hernando", st:"FL", lat:28.53049, lng:-82.39369, city:"Brooksville", url:"", address:"7120 Hope Hill Rd, Brooksville, FL 34601", phone:"(352) 799-5930", when:"Thurs, 9am–12:30pm (bring ID)", services:["food"], notes:"Also runs the DayStar Life Center Thrift Shops (see Clothing) which fund this pantry. Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Fellowship Community Church", category:"food", county:"Hernando", st:"FL", lat:28.46162, lng:-82.53718, city:"Spring Hill", url:"", address:"11250 Spring Hill Dr, Spring Hill, FL 34609", phone:"(352) 686-4612", when:"2nd Wed, 10am–1pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"First Baptist Church of Spring Hill", category:"food", county:"Hernando", st:"FL", lat:28.44172, lng:-82.60385, city:"Spring Hill", url:"", address:"7279 Pinehurst Dr, Spring Hill, FL 34606", phone:"(352) 683-2863", when:"4th Tues, 9:30am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"First Presbyterian Church (Brooksville)", category:"food", county:"Hernando", st:"FL", lat:28.55801, lng:-82.38374, city:"Brooksville", url:"", address:"250 Bell Ave, Brooksville, FL 34601", phone:"(352) 796-4228", when:"2nd Thurs, 11am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Hillside Community Baptist Church", category:"food", county:"Hernando", st:"FL", lat:28.52306, lng:-82.28092, city:"Brooksville", url:"", address:"27440 Cortez Blvd, Brooksville, FL 34602", phone:"(352) 799-0687", when:"Call for appt — Wed 4–5:30pm & Sat 12–3pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Forest Oaks Lutheran Church", category:"food", county:"Hernando", st:"FL", lat:28.48769, lng:-82.57820, city:"Spring Hill", url:"", address:"8555 Forest Oaks Blvd, Spring Hill, FL 34606", phone:"(352) 683-9731", when:"Tues, 9am–noon (drive-thru, bring ID)", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Grace Presbyterian & St. Marks", category:"food", county:"Hernando", st:"FL", lat:28.45545, lng:-82.58044, city:"Spring Hill", url:"", address:"8375 Spring Hill Dr, Spring Hill, FL 34608", phone:"(352) 683-2082", when:"Tues, 9–11am", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Grace World Outreach Church", category:"food", county:"Hernando", st:"FL", lat:28.53843, lng:-82.39301, city:"Brooksville", url:"", address:"20366 Cortez Blvd, Brooksville, FL 34601", phone:"(352) 796-3685", when:"3rd Sat, 9–11am", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Greater Love Outreach Ministries", category:"food", county:"Hernando", st:"FL", lat:28.578, lng:-82.40298, city:"Brooksville", url:"", address:"20053 Yontz Rd, Brooksville, FL 34601", phone:"(352) 585-7328", when:"Tues & Thurs, 10am–1pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Holy Cross Lutheran Church", category:"food", county:"Hernando", st:"FL", lat:28.45589, lng:-82.61717, city:"Spring Hill", url:"", address:"6193 Spring Hill Dr, Spring Hill, FL 34606", phone:"(352) 683-9016", when:"Mon, 9:30am–12:30pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Holy Trinity Lutheran Church", category:"food", county:"Hernando", st:"FL", lat:28.45192, lng:-82.45169, city:"Masaryktown", url:"", address:"1214 Broad St, Masaryktown, FL 34604", phone:"(352) 796-4066", when:"Tues, 9–11:45am", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Life Church Spring Hill", category:"food", county:"Hernando", st:"FL", lat:28.43362, lng:-82.50373, city:"Spring Hill", url:"", address:"18924 County Line Rd, Spring Hill, FL 34610", phone:"(352) 799-2821", when:"Fri, 3–6pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Mariner United Methodist Church", category:"food", county:"Hernando", st:"FL", lat:28.52997, lng:-82.51163, city:"Spring Hill", url:"", address:"7079 Mariner Blvd, Spring Hill, FL 34609", phone:"(352) 596-0080", when:"Mon & Thurs, 9–11am (curbside)", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Nativity Lutheran Church", category:"food", county:"Hernando", st:"FL", lat:28.52387, lng:-82.57149, city:"Weeki Wachee", url:"", address:"6363 Commercial Way, Weeki Wachee, FL 34613", phone:"(352) 597-1456", when:"Wed & Thurs, 9:30am–1pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"New Hope Assembly of God", category:"food", county:"Hernando", st:"FL", lat:28.52307, lng:-82.27876, city:"Brooksville", url:"", address:"27488 Cortez Blvd, Brooksville, FL 34602", phone:"(352) 544-0786", when:"3rd Thurs, 9am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Northcliff Church", category:"food", county:"Hernando", st:"FL", lat:28.49411, lng:-82.54768, city:"Spring Hill", url:"", address:"10515 Northcliffe Blvd, Spring Hill, FL 34608", phone:"(352) 683-5882", when:"Tues 2–4pm, Thurs 10am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Providence Church", category:"food", county:"Hernando", st:"FL", lat:28.51395, lng:-82.51839, city:"Spring Hill", url:"", address:"6000 Mariner Blvd, Spring Hill, FL 34609", phone:"(352) 556-2490", when:"Fri, 10am–noon", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Ridge Manor United Methodist Church", category:"food", county:"Hernando", st:"FL", lat:28.50776, lng:-82.17573, city:"Ridge Manor", url:"", address:"34350 Cortez Blvd, Ridge Manor, FL 33523", phone:"(352) 583-3770", when:"1st & 3rd Mon, 4–5:30pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Spring Hill Calvary Church (Nazarene)", category:"food", county:"Hernando", st:"FL", lat:28.43572, lng:-82.60204, city:"Spring Hill", url:"", address:"235 Cobblestone Rd, Spring Hill, FL 34606", phone:"(352) 683-0587", when:"2nd & 4th Tues, 11am–1pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Spring Hill Seventh Day Adventist Church", category:"food", county:"Hernando", st:"FL", lat:28.46098, lng:-82.63631, city:"Spring Hill", url:"", address:"2300 Osowaw Blvd, Spring Hill, FL 34607", phone:"(352) 686-1143", when:"2nd & 4th Sun, 12–2pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Spring Life Church", category:"food", county:"Hernando", st:"FL", lat:28.45505, lng:-82.56506, city:"Spring Hill", url:"", address:"9344 Spring Hill Dr, Spring Hill, FL 34608", phone:"(352) 683-2600", when:"Wed, 9am–2pm", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"YMCA (Spring Hill) — partner food pantry", category:"food", county:"Hernando", st:"FL", lat:28.45368, lng:-82.5392, city:"Spring Hill", url:"", address:"1300 Mariner Blvd, Spring Hill, FL 34609", phone:"(352) 688-9622", when:"1st Thurs, 4:30pm", services:["food"], notes:"Listed on PHP's countywide pantry sheet (dated Oct 2021) — atypical for a YMCA branch to run a pantry directly, so confirm this is still active before relying on it." },
  { name:"Church of God of Prophecy — Firstfruits Food Pantry", category:"food", county:"Hernando", st:"FL", lat:28.53405, lng:-82.40727, city:"Brooksville", url:"", address:"15444 Wiscon Rd, Brooksville, FL 34601", phone:"(352) 345-1990 / (352) 345-2956", when:"Call for schedule", services:["food"], notes:"Source: PHP countywide pantry sheet (dated Oct 2021) — call ahead to confirm this schedule is still active." },
  { name:"Florida Food Force", category:"food", county:"Hillsborough", st:"FL", lat:28.19668, lng:-82.62453, city:"Odessa", url:"https://floridafoodforce.org", address:"11523 Prosperous Dr, Odessa, FL 33556", phone:"(727) 261-7422", org:"Florida Food Force, Inc.", verified:"2026-08-03", services:["food"], notes:"HQ is in Hillsborough County (not Hernando), but the weekly supplemental food program has no income or county restriction and reaches into the Nature Coast — worth calling. Office hours Mon–Wed 9am–3pm." },

  // ---- CLOTHING / THRIFT (voucher & free-goods programs) ----
  { name:"St. Vincent de Paul — Second Location (unconfirmed)", category:"clothing", county:"Hernando", st:"FL", lat:28.43132, lng:-82.46314, city:"Spring Hill", url:"", address:"18810 US-41, Spring Hill, FL", phone:"(352) 796-6606", org:"St. Vincent de Paul (SVDP)", notes:"Unclear whether this is a second store or a conference/casework office — call to confirm before visiting." },
  { name:"Salvation Army Family Store", category:"clothing", county:"Hernando", st:"FL", lat:28.48465, lng:-82.6052, city:"Spring Hill", url:"https://tampa.salvationarmyflorida.org", address:"3570 Commercial Way (US-19), Spring Hill, FL", phone:"(352) 666-9009", org:"The Salvation Army", verified:"2026-08-03", services:["clothing"], notes:"Emergency vouchers for free clothing/furniture/housewares are issued by a caseworker at the Brooksville office (352-796-1186), not at the store counter — get the voucher first." },
  { name:"Goodwill Spring Hill Superstore", category:"clothing", county:"Hernando", st:"FL", lat:28.49703, lng:-82.59127, city:"Spring Hill", url:"", address:"4750 Commercial Way, Spring Hill, FL", phone:"(352) 596-1712", services:["clothing"], notes:"Standard low-cost thrift, not a voucher program — worth checking for periodic community giveaway events." },
  { name:"Jericho Road Thrift Store — County Line Rd", category:"clothing", county:"Hernando", st:"FL", lat:28.43377, lng:-82.56659, city:"Spring Hill", url:"https://www.jericho-road.net", address:"15000 County Line Rd, Spring Hill, FL", phone:"(352) 799-2912", org:"Jericho Road Ministries", services:["clothing"], notes:"Sales fund Jericho Road Ministries' shelter and recovery programs; ask about direct clothing help." },
  { name:"Jericho Road Thrift Store — Commercial Way", category:"clothing", county:"Hernando", st:"FL", lat:28.5043, lng:-82.58705, city:"Spring Hill", url:"https://www.jericho-road.net", address:"5260 Commercial Way, Spring Hill, FL", phone:"(352) 799-2912", org:"Jericho Road Ministries", services:["clothing"], notes:"Second Jericho Road Ministries thrift location; ask about direct clothing help." },
  { name:"DayStar Life Center Thrift Shops", category:"clothing", county:"Hernando", st:"FL", lat:28.53808, lng:-82.39138, city:"Brooksville", url:"", address:"20428 Cortez Blvd, Brooksville, FL", phone:"(352) 799-5930", org:"Day Star Life Center", services:["clothing"], notes:"Thrift sales fund DayStar's food pantry program (see Day Star Life Center under Food); also accepts donations." },

  // ---- PET FOOD ----
  { name:"Humane Society of the Nature Coast — Little Pet Pantry", category:"pet", county:"Hernando", st:"FL", lat:28.53398, lng:-82.42462, city:"Brooksville", url:"https://humanerescue.org", address:"7200 Mobley Rd, Brooksville, FL 34601", phone:"(352) 796-2711", org:"Humane Society of the Nature Coast", verified:"2026-08-03", services:["petfood"], notes:"Free self-serve pet food pantry just outside the shelter's main gate for Hernando County residents struggling to feed pets, first-come first-served — ask staff if it's empty. Shelter hours Mon–Tue & Thu–Sun 11am–5pm (closed Wed). Several human food pantries above also report occasional donated pet food — worth asking, especially at Feeding Tampa Bay mobile distributions." },

  // ---- TRANSPORTATION ----
  { name:"TheBus (Hernando County Transit) — Operations Office", category:"transportation", county:"Hernando", st:"FL", lat:28.54562, lng:-82.37694, city:"Brooksville", url:"https://www.hernandocounty.us", address:"700 Aeriform Dr, Brooksville, FL 34601", phone:"(352) 754-4444", org:"Hernando County Transit", email:"thebus@hernandocounty.us", verified:"2026-08-03", services:["transportation"], notes:"No dedicated homeless bus-voucher program listed publicly, but two reliable paths to free/reduced fares: (1) Reduced-Fare Photo ID for seniors 65+, students, and people with disabilities — form + ID at this office; (2) case-manager-issued bus passes — ask a PHP, Salvation Army, or Catholic Charities caseworker. Fares via the Token Transit app or cash on board; fare-capping auto-upgrades you to a cheaper pass type once you've paid enough in a day. Trans-Hernando door-to-door paratransit is run separately by Mid-Florida Community Services (see Hubs) — standard fare $5/$10 round trip, reduced by income/employment/veteran status ($1 each way for veterans and their families), reservations (352) 799-1510." },

  // ---- COORDINATING / ADVOCACY AGENCIES ----
  { name:"Mid Florida Homeless Coalition (Regional HQ — Continuum of Care Lead)", category:"coalition", county:"Citrus", st:"FL", lat:28.83582, lng:-82.33037, city:"Inverness", url:"https://midfloridahomeless.org", address:"1512 US-41, Inverness, FL 34450 (pin is Inverness city center — exact address didn't resolve on the geocoders used; street address is otherwise correct per the org's own site)", phone:"(352) 860-2308", org:"Mid Florida Homeless Coalition, Inc.", email:"info@midflhc.org", verified:"2026-08-03", services:["housing","casework"], notes:"HQ is in Citrus County, not Hernando, but this is the official HUD Continuum of Care lead agency for Citrus, Hernando, Lake, and Sumter counties — the entry point for coordinated-entry housing placement and diversion/wrap-around services. As of late-2025 reporting, MFHC's own leadership described Hernando County service capacity as \"pretty narrow in scope\" — meaning MFHC is the right place to call to get connected/assessed, but persistence and follow-up matter given limited local shelter capacity. Office hours Mon–Fri 8am–5pm." },
  { name:"Hernando Community Coalition (houses the Hernando Homeless Initiative)", category:"coalition", county:"Hernando", st:"FL", lat:28.4671, lng:-82.51121, city:"Spring Hill", url:"https://hernandocommunitycoalition.org", address:"13001 Spring Hill Dr, Spring Hill, FL 34609", phone:"(352) 596-8000", org:"Hernando Community Coalition", verified:"2026-08-03", services:["casework"], notes:"Countywide behavioral-health partnership; also the host organization for the Hernando Homeless Initiative (HHI, started ~2023) — a task force combining PHP, this Coalition, and other local nonprofits to coordinate transportation to services, sanitation partnerships with the county, and joint \"one-stop-shop\" events (legal aid, medical/dental/vet care, mobile showers, VA advocate services). Watch PHP's Facebook page or this org's site for HHI event dates; HHI contact is Tresa Watson via this office." },

  // ---- HOTLINES / CRISIS LINES ----
  { name:"211 / First Contact (Crisis & Referral Line)", category:"hotline", county:"Hernando", st:"FL", lat:28.5546, lng:-82.3903, city:"Brooksville", url:"https://www.firstcontact.org", address:"Phone/online service — no single physical address in Hernando County; pin shows Brooksville, the county seat", phone:"Dial 211 · (727) 562-1543 (cell-phone access)", org:"First Contact (formerly 211 Tampa Bay Cares)", verified:"2026-08-03", services:["casework","housing","food"], notes:"24/7, 100+ languages. The single best all-purpose number to call first if you're not sure where to start — operators can check real-time bed/pantry availability across Hernando County." }
];
